name: Continuous Integration

on:
  push:
    branches:
      - master
      - testing
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@latest
        
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@latest
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
          
      - name: Show version
        run: echo "Version is ${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }}"