mode: ContinuousDeployment
branches:
  master:
    regex: ^master$
    mode: ContinuousDeployment
    increment: Major
    is-mainline: true
    tracks-release-branches: false
    is-release-branch: false
  testing:
    regex: ^testing$
    mode: ContinuousDeployment
    increment: Minor
    source-branches:
      - develop
    is-mainline: false
    tracks-release-branches: false
    is-release-branch: false
  develop:
    regex: ^develop$
    mode: ContinuousDeployment
    increment: Patch
    source-branches:
      - testing
    is-mainline: false
    tracks-release-branches: false
    is-release-branch: false
