mode: Mainline
branches:
  master:
    regex: ^master$
    increment: Major
    pre-release-weight: 55000
  testing:
    regex: ^testing$
    increment: Minor
    pre-release-weight: 30000
  develop:
    regex: ^develop$
    increment: Patch
    is-mainline: true
    pre-release-weight: 0
