mode: Mainline
commit-message-incrementing: MergeMessageOnly
branches:
  main:
    regex: ^master$
    tag: ''
  feature:
    regex: ^testing$
    tag: useBranchName
    increment: Minor
  hotfix:
    regex: ^develop$
    tag: useBranchName
    increment: Patch