mode: Mainline
commit-message-incrementing: MergeMessageOnly
branches:
  master:
    regex: ^master$
    tag: useBranchName
    is-develop: true
    increment: Major
  testing:
    regex: ^testing$
    tag: useBranchName
    is-develop: true
    increment: Minor
  develop:
    regex: ^develop$
    tag: useBranchName
    is-develop: true
    increment: Patch