mode: Mainline
branches:
  master:
    regex: ^master$
    increment: Major
    source-branches:
      - testing
    pre-release-weight: 55000
  testing:
    regex: ^testing$
    increment: Minor
    source-branches:
      - develop
    pre-release-weight: 30000
  develop:
    regex: ^develop$
    increment: Patch
    is-mainline: true
    pre-release-weight: 0
