name: Continuous Integration

on:
  push:
    branches:
      - master
      - testing
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.x'
        
      - name: Debug  
        run: ls -la
        
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          useConfigFile: true
          # configFilePath: ../gitversion.yaml
        
      - name: Show version
        run: echo "Version is ${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }}"
